// export const ENTRANCE_ACTION = "ENTRANCE_ACTION";
// export const HIDE_BLOCK_ENTRANCE = "HIDE_BLOCK_ENTRANCE";
// export const HIDE_BLOCK_REGISTRATION = "HIDE_BLOCK_REGISTRATION";
// export const REGISTRATION_ACTION = "REGISTRATION_ACTION";